spring.application.name=ecommerce-tech
server.port=8081
logging.level.org.flywaydb=DEBUG

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Keep Flyway/Hibernate synced
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true