spring.application.name=ecommerce-tech
server.port=8081
logging.level.org.flywaydb=DEBUG

# Database Connection
spring.datasource.url=${DB_URL_CONNECTION}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

# Turn off Hibernate Schema Generation (Let Flyway own it)
spring.jpa.hibernate.ddl-auto=validate

# Flyway Configuration
spring.flyway.enabled=true
